#! /usr/bin/env python
#
#   Graph plotting libary using matplotlib
#
# @author: Sreejith K
# Created on 10th Nov 2010

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure

def plot(xlist, ylist, name):
    # plot a graph using given x and y dimensions
    fig = Figure()
    ax = fig.add_subplot(111)
    ax.plot(xlist, ylist, 'bo-')
    print dir(ax.xaxis.convert_xunits)
    print dir(ax.xaxis)
    canvas = FigureCanvas(fig)
    canvas.print_png(name)

def linear_plot(ylist, name):
    # plot a graph using given y dimensions. x dimension list is autogenerated
    #   from the length of the y dimension list
    xlist = range(len(ylist))
    plot(xlist, ylist, name)

if __name__ == '__main__':
    import random
    # plot with x and y
    xlist = [random.randint(0, 100) for foo in range(100)]
    ylist = [random.randint(0, 100) for foo in range(100)]
    plot(xlist, ylist, 'sample.png')
    
    # plot with y
    ylist = [random.randint(0, 100) for foo in range(100)]
    linear_plot(ylist, 'sample_linear.png')
